---

include:
  - template: SAST.gitlab-ci.yml

stages:
  - lint
  - tests
  - deploy

variables:
  PASS_VERSION: 1.7.3


# Dependencies definitions
# ------------------------

.script: &script
  stage: tests
  script:
    - pip3 install green coverage requests zxcvbn
    - make tests

.only: &only
  only:
   - tags
   - web


# Jobs definitions
# ----------------

# Code Linter

bash:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - shellcheck --shell=bash audit.bash

python:
  stage: lint
  image: python:latest
  before_script:
    - pip install prospector[with_everything] requests zxcvbn
  script:
    - make lint

sast:
  stage: lint

# Code tests

archlinux:
  image: archlinux/base
  before_script:
    - pacman -Syu --noconfirm --noprogressbar make python-pip which grep pass
  <<: *script
  artifacts:
    expire_in: 1 day
    paths:
      - htmlcov/

ubuntu:
  image: ubuntu
  before_script:
    - apt-get update -q && apt-get install -y make pass python3-pip grep
  <<: *script
  <<: *only

debian:
  image: debian
  before_script:
    - apt-get update -q && apt-get install -y make pass python3-pip grep wget
    - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
    - tar -xf password-store-$PASS_VERSION.tar.xz
    - make --directory=password-store-$PASS_VERSION install
  <<: *script
  <<: *only

fedora:
  image: fedora
  before_script:
    - dnf -y install --setopt=install_weak_deps=False make gpg pass python3-pip grep which
  <<: *script
  <<: *only

# Code coverage deployment

pages:
  stage: deploy
  dependencies:
    - archlinux
  script:
    - mv htmlcov/ public/
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - master
