---

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - lint
  - tests
  - dist
  - deploy

variables:
  PASS_VERSION: 1.7.3


# Dependencies definitions
# ------------------------

.pass: &pass
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xf password-store-$PASS_VERSION.tar.xz
  - make --directory=password-store-$PASS_VERSION install


.script:
  script:
    - pip3 install green coverage requests zxcvbn
    - make tests
    - make
    - make install
    - cd ~
    - pass audit --help

.tests:
  extends: .script
  stage: tests
  before_script:
    - apt-get update -q && apt-get install -y make pass python3-pip grep

.distribution:
  extends: .script
  stage: dist
  only:
   - tags
   - web


# Jobs definitions
# ----------------

# Code Linter

bash:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - shellcheck --shell=bash audit.bash

prospector:
  stage: lint
  image: python:latest
  allow_failure: True
  before_script:
    - pip install prospector[with_everything] requests zxcvbn
  script:
    - make lint

sast:
  stage: lint

# Code tests

python 3.10:
  image: python:3.10
  extends: .tests
  coverage: '/\d+\%\s*$/'
  artifacts:
    expire_in: 2 days
    paths:
      - htmlcov/

python 3.9:
  image: python:3.9
  extends: .tests

python 3.8:
  image: python:3.8
  extends: .tests

python 3.7:
  image: python:3.7
  extends: .tests

python 3.6:
  image: python:3.6
  extends: .tests

# Distribution tests

archlinux:
  image: archlinux
  extends: .distribution
  before_script:
    - pacman -Syu --noconfirm --noprogressbar make python-pip which grep pass

ubuntu:
  image: ubuntu
  extends: .distribution
  before_script:
    - apt-get update -q && apt-get install -y make pass python3-pip grep

debian:
  image: debian
  extends: .distribution
  before_script:
    - apt-get update -q && apt-get install -y make pass python3-pip grep wget
    - *pass

fedora:
  image: fedora
  extends: .distribution
  before_script:
    - dnf -y install --setopt=install_weak_deps=False make gpg pass python3-pip grep which

# Code coverage deployment

pages:
  stage: deploy
  dependencies:
    - python 3.10
  script:
    - mv htmlcov/ public/
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - master
