---

output-format: text

ignore-patterns:
  - (^|/)\..+

pylint:
  disable:
    - invalid-name
    - too-few-public-methods

pep257:
  disable:
    - D100
    - D107
    - D203
    - D204
    - D213
